CREATE DATABASE IF NOT EXISTS Tech4Girls_DB;
SHOW DATABASES;
USE Tech4Girls_DB;

CREATE TABLE IF NOT EXISTS Users (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO Users (username, email)
VALUES ('adjoa', 'adjoa@example1.com');

SHOW TABLES;
SELECT * FROM Users;